jenkins:
  systemMessage: "Jenkins ready"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin123"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('app-pipeline') {
        triggers {
          githubPush()
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/ThetaAim/devops-production-lab.git')
                }
                branch('*/main')
              }
            }
            scriptPath('ci/jenkins/Jenkinsfile')
          }
        }
      }
