pipeline {
    agent any

    environment {
        AWS_REGION = "eu-central-1"
        ECR_REPO   = "devops-lab-app"
    }

    stages {

        stage('Checkout code') {
            steps {
                git branch: 'main', url: 'https://github.com/ThetaAim/devops-production-lab.git'
            }
        }

        stage('Check changes') {
            steps {
                script {
                    def changes = sh(
                        script: "git diff --name-only HEAD~1 HEAD",
                        returnStdout: true
                    ).trim()

                    echo "Changed files:\n${changes}"

                    if (!changes.contains("services/app")) {
                        echo "No changes in services/app — stopping pipeline"
                        currentBuild.result = 'NOT_BUILT'
                        error("Skipping build")
                    }
                }
            }
        }

        stage('Prepare variables') {
            steps {
                script {
                    env.GIT_COMMIT_SHORT = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()

                    env.ACCOUNT_ID = sh(
                        script: "aws sts get-caller-identity --query Account --output text",
                        returnStdout: true
                    ).trim()
                }
            }
        }

        stage('Build Docker image') {
            steps {
                sh '''
                docker build -t app-image ./services/app
                '''
            }
        }
        
        stage('Test Build') {
          steps {
           sh '''
             docker rm -f test-app || true
             docker run -d \
             --name test-app \
             --network app-net \
             app-image
             
             for i in {1..10}; do
               if curl -sf http://test-app > /dev/null; then
                 echo "App is ready"
                 exit 0
               fi
               sleep 1
             done
             
               echo "App failed to start"
               docker logs test-app
               exit 1
             
             '''   
           
          }
        }   
        

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Tag image') {
            steps {
                sh '''
                docker tag app-image \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$GIT_COMMIT_SHORT
               
                docker tag app-image \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
                '''
            }
        }

        stage('Push image') {
            steps {
                sh '''
                docker push \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$GIT_COMMIT_SHORT

                docker push \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
                '''
            }
        }
    }
}
